classdef AddDataStoreView < appbox.View

    events
        Add
        Cancel
    end

    properties (Access = private)
        urlField
        userField
        passwordField
        addButton
        cancelButton
    end

    methods

        function createUi(obj)
            import appbox.*;

            set(obj.figureHandle, ...
                'Name', 'Add Data Store', ...
                'Position', screenCenter(hpix(330/11), vpix(139/16)), ...
                'Resize', 'off');

            mainLayout = uix.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 11);

            storeLayout = uix.Grid( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            Label( ...
                'Parent', storeLayout, ...
                'String', 'URL:');
            Label( ...
                'Parent', storeLayout, ...
                'String', 'User:');
            Label( ...
                'Parent', storeLayout, ...
                'String', 'Password:');
            obj.urlField = uicontrol( ...
                'Parent', storeLayout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.userField = uicontrol( ...
                'Parent', storeLayout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.passwordField = PasswordField( ...
                'Parent', storeLayout);
            set(storeLayout, ...
                'Widths', [hpix(60/11) -1], ...
                'Heights', [vpix(23/16) vpix(23/16) vpix(23/16)]);

            % Add/Cancel controls.
            controlsLayout = uix.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uix.Empty('Parent', controlsLayout);
            obj.addButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Add', ...
                'Interruptible', 'off', ...
                'Callback', @(h,d)notify(obj, 'Add'));
            obj.cancelButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Interruptible', 'off', ...
                'Callback', @(h,d)notify(obj, 'Cancel'));
            set(controlsLayout, 'Widths', [-1 hpix(75/11) hpix(75/11)]);

            set(mainLayout, 'Heights', [-1 vpix(23/16)]);

            % Set clone button to appear as the default button.
            try %#ok<TRYNC>
                h = handle(obj.figureHandle);
                h.setDefaultButton(obj.cloneButton);
            end
        end

        function u = getUrl(obj)
            u = get(obj.urlField, 'String');
        end

        function requestUrlFocus(obj)
            obj.update();
            uicontrol(obj.urlField);
        end

        function u = getUser(obj)
            u = get(obj.userField, 'String');
        end

        function p = getPassword(obj)
            p = get(obj.passwordField, 'String');
        end

    end

end
